In [1]:
from pyhdf.SD import SD, SDC
import h5py
import os
import pandas as pd
import numpy as np

In [2]:
os.chdir('/Users/jackpeele/Documents/Data Science/NASA/atrain-cloudseg/src/utils')

In [3]:
import icare

In [4]:
session = icare.ICARESession('/Users/jackpeele/Documents/Data Science/NASA/HDF')
folder = session.listdir('PARASOL/L1_B-HDF/2010/2010_03_02/')

ICARE Username: jpeele
ICARE Password: ···············

In [ ]:
root = 'PARASOL/L1_B-HDF/2010/2010_03_02/'

for data in folder:
    path = session.get_file(root + data)
    #print(path)
    file = h5py.File(path, 'r')
    lat = pd.DataFrame(file['Geolocation_Fields']['Latitude'])
    for row in range(len(lat)):
        for col in range(len(lat.columns)):
             if (lat.loc[row][col] > 30) & (lat.loc[row][col] < 40):
                print(path)
                
    print('Next')

In [5]:
new_path = session.get_file('PARASOL/L1_B-HDF/2010/2010_03_02/POLDER3_L1B-BG1-120133M_2010-03-02T00-49-22_V1-01.h5')
new_file = h5py.File(new_path, 'r')

In [6]:
new_file['Geolocation_Fields'].keys()

In [7]:
df = pd.DataFrame(new_file['Geolocation_Fields']['Latitude'])

In [10]:
df

,0,1,2,3,4,5,6,7,8,9,...,6470,6471,6472,6473,6474,6475,6476,6477,6478,6479
0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
1,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
2,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
4,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3236,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3237,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3238,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3239,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [24]:
# T 17-20-38